// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Suk1JLF_zItiLQOYjcn7L5ehKyA3K_I',
    appId: '1:60810143543:web:9916ad40ab16fd50cb5cb2',
    messagingSenderId: '60810143543',
    projectId: 'deliveryproject-988ac',
    authDomain: 'deliveryproject-988ac.firebaseapp.com',
    storageBucket: 'deliveryproject-988ac.appspot.com',
    measurementId: 'G-YYSDWX885Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA6hbhkZz1vOnCZDUW7ERZBVroJceJ8-U',
    appId: '1:60810143543:android:2513dc81828654a1cb5cb2',
    messagingSenderId: '60810143543',
    projectId: 'deliveryproject-988ac',
    storageBucket: 'deliveryproject-988ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-y4dyu4Sn78zmHctO2o0rvMlmQcBlBck',
    appId: '1:60810143543:ios:b70909353babfbd2cb5cb2',
    messagingSenderId: '60810143543',
    projectId: 'deliveryproject-988ac',
    storageBucket: 'deliveryproject-988ac.appspot.com',
    iosBundleId: 'com.example.deliveryproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-y4dyu4Sn78zmHctO2o0rvMlmQcBlBck',
    appId: '1:60810143543:ios:b70909353babfbd2cb5cb2',
    messagingSenderId: '60810143543',
    projectId: 'deliveryproject-988ac',
    storageBucket: 'deliveryproject-988ac.appspot.com',
    iosBundleId: 'com.example.deliveryproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Suk1JLF_zItiLQOYjcn7L5ehKyA3K_I',
    appId: '1:60810143543:web:bb45532f8fb766cbcb5cb2',
    messagingSenderId: '60810143543',
    projectId: 'deliveryproject-988ac',
    authDomain: 'deliveryproject-988ac.firebaseapp.com',
    storageBucket: 'deliveryproject-988ac.appspot.com',
    measurementId: 'G-60KMS0TB53',
  );
}
